### ISSUE TITLE
Question about string concatenation... 

### ISSUE THREAD

**Issue by duarteocarmo** [veekaybee/viberary#101]
https://github.com/veekaybee/viberary/blob/74390f0d30288adbe77af34243ae3605a9a19259/src/model/generate_training_data.py#L81

Shouldn't we include some spaces here? Example: 

If the following data were in the tables:

- review_text: "This is a fantastic book."
- goodreads_auth_ids.title: "Book Title"
- goodreads_auth_ids.description: "A thrilling story about adventure."
- goodreads_authors.name: "John Doe"

The resulting value in the sentence column for this record would be:

"This is a fantastic book.Book TitleA thrilling story about adventure.John Doe"

**Comment by veekaybee** [comment]
Great find! We can and we should. I'm actually curious how much this will change the results since BERT uses Wordpiece to create subtokens, [which has its own rules](https://huggingface.co/learn/nlp-course/chapter6/6?fw=pt) for grouping/ignoring/paying attention to spaces and punctuation. I'd need to do an eval on this, which would take some time. Stay tuned!

**Comment by veekaybee** [comment]
Closing this out - going into maintenance mode on this project https://vickiboykis.com/2024/01/05/retro-on-viberary/
